### ISSUE TITLE
update rawspeed ? 

### ISSUE THREAD

**Issue by sergiomb2** [rawstudio/rawstudio#5]
how about update rawspeed sub module ? 
https://github.com/rawstudio/rawstudio/tree/master/plugins/load-rawspeed
since commit 8ea2a3a ,  is 217 commits behind develop branch

**Comment by sergiomb2** [comment]
Hi, another question about this subject , can we compile rawstudio with rawspeed as external library ? i.e 
install rawspeed in system and compile  rawstudio with that rawspeed  ? unblundle rawspeed from rawstudio package .

Thanks.

**Comment by sergiomb2** [comment]
with this commit : 
https://github.com/sergiomb2/rawstudio/commit/7926c05ebc9afa091186b2fadcbd43551fe1cea9

    #0  0x00007ffff307aa98 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
    #1  0x00007ffff307c69a in __GI_abort () at abort.c:89
    #2  0x00007ffff47a99e5 in g_assertion_message (domain=domain@entry=0x0,  file=file@entry=0x7ffff7bcc08d "rs-plugin-manager.c", line=line@entry=56, func=func@entry=0x7ffff7bcc340 <__func__.56808> "rs_plugin_manager_load_all_plugins", message=message@entry=0x5555558c7100 "assertion failed: (g_type_module_use(G_TYPE_MODULE(plugin)))") at gtestutils.c:2429
    #3  0x00007ffff47a9a7a in g_assertion_message_expr (domain=domain@entry=0x0, file=file@entry=0x7ffff7bcc08d "rs-plugin-manager.c", line=line@entry=56, func=func@entry=0x7ffff7bcc340 <__func__.56808> "rs_plugin_manager_load_all_plugins", expr=expr@entry=0x7ffff7bcc190 "g_type_module_use(G_TYPE_MODULE(plugin))") at gtestutils.c:2444
    #4  0x00007ffff7bb5dab in rs_plugin_manager_load_all_plugins () at rs-plugin-manager.c:56
    #5  0x0000555555569156 in main (argc=1, argv=0x7fffffffdac8) at application.c:648

any hint ?

**Comment by sergiomb2** [comment]
done here https://github.com/sergiomb2/rawstudio/commit/ff3aaaed9d0ca18bd2c59b07522225a6d1cb4e3b 

is working !
