### ISSUE TITLE
Coredump on launch

### ISSUE THREAD

**Issue by hedgehog1029** [rawstudio/rawstudio#50]
```
~ ➥ rawstudio 
**
ERROR:rs-metadata.c:605:rs_metadata_dotdir_helper: assertion failed: ((dotdir = rs_dotdir_get(filename)))
[1]    8449 abort (core dumped)  rawstudio
```
Rawstudio has been working great for ages, but while batch exporting it crashed and now will not open.
I have since restarted my PC which has not fixed the problem.

**Comment by hedgehog1029** [comment]
Backtrace:
```
#0  0x00007ffff461d86b in raise () at /usr/lib/libc.so.6
#1  0x00007ffff460840e in abort () at /usr/lib/libc.so.6
#2  0x00007ffff58c8b76 in g_assertion_message () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff58c8bdc in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7ba69b2 in rs_metadata_dotdir_helper () at /usr/lib/librawstudio-2.1.so
#5  0x00007ffff7ba705d in  () at /usr/lib/librawstudio-2.1.so
#6  0x00007ffff7ba791f in rs_metadata_new_from_file () at /usr/lib/librawstudio-2.1.so
#7  0x0000555555579bf7 in  ()
#8  0x000055555557a6c3 in  ()
#9  0x0000555555572ce3 in  ()
#10 0x0000555555565587 in main ()
```

**Comment by abrander** [comment]
This is almost two years old. @hedgehog1029 Please re-open if you can still reproduce.
